name: latest-deployment
channels:
  - conda-forge
  - openeye

dependencies:
    # Base depends
  - openff-toolkit-examples

  - openmmforcefields
  - openeye-toolkits
  - qcportal >=0.15
  - pytest
  - pytest-rerunfailures
  - nbval
