name: latest-deployment
channels:
  - conda-forge/label/openff-interchange_rc
  - conda-forge
dependencies:
    # Base depends
  - openff-toolkit-examples
    # Tests
  - pytest=7.4
  - pytest-rerunfailures
  - nbval
  - parmed=3
