name: latest-deployment
channels:
  - conda-forge
  - openeye
dependencies:
    # Base depends
  - openff-toolkit-examples
    # Tests
  - openeye-toolkits
  - pytest=8
  - pytest-rerunfailures
  - nbval
  # https://github.com/openforcefield/openff-toolkit/issues/1532
  # - parmed=3
