name: latest-deployment
channels:
  - conda-forge
  - openeye
dependencies:
    # Base depends
  - openff-toolkit-examples
    # Tests
  - openeye-toolkits =2024.1.0
  - pytest=7.4
  - pytest-rerunfailures
  - nbval
  - parmed=3
