name: latest-deployment
channels:
  - conda-forge/label/openff-interchange_dev
  - conda-forge
dependencies:
  - openff-interchange-base =0.4.11
    # Base depends
  - openff-toolkit-examples
    # Tests
  - pytest=7.4
  - pytest-rerunfailures
  - nbval
  # Remove once https://github.com/ParmEd/ParmEd/pull/1387 gets into a release
  - numpy <2.3
  # No idea why this is necessary, see https://github.com/openforcefield/openff-toolkit/pull/1821
  - nomkl
