name: latest-deployment
channels:
  - conda-forge/label/openff-interchange_dev
  - conda-forge
  - openeye
dependencies:
  - openff-interchange-base =0.4.11
    # Base depends
  - openff-toolkit-examples
    # Tests
  - openeye-toolkits
  - pytest=7.4
  - pytest-rerunfailures
  - nbval
  # Remove once https://github.com/ParmEd/ParmEd/pull/1387 gets into a release
  # This is brought in indirectly by openff-toolkit-examples
  # parmed <- openff-toolkit-examples <- openff-toolkit <- ambertools
  - numpy <2.3
