name: test
channels:
  - conda-forge
  - conda-forge/label/openff-toolkit_rc
  - conda-forge/label/openff-interchange_rc

dependencies:
    # Base depends
  - openff-toolkit

  - openmmforcefields
  - pytest
  - pytest-rerunfailures
  - nbval
