name: 010x-latest-deployment
channels:
  - conda-forge


dependencies:
    # Base depends
  - openff-toolkit-examples =0.10

  - openmmforcefields
  - qcportal >=0.15
  - py  # Remove after pytest 7.2 dust settles
  - pytest
  - pytest-rerunfailures
  - nbval
