name: latest-deployment
channels:
  - conda-forge
dependencies:
    # Base depends
  - openff-toolkit-examples
    # Tests
  - pytest=8
  - pytest-rerunfailures
  - nbval
  # https://github.com/openforcefield/openff-toolkit/issues/1532
  #- parmed=3