name: latest-deployment
channels:
  - conda-forge/label/openff-interchange_rc
  - conda-forge
  - openeye
dependencies:
    # Base depends
  - openff-toolkit-examples
    # Tests
  - openeye-toolkits
  - pytest=7.4
  - pytest-rerunfailures
  - nbval
  - parmed=3
