name: latest-deployment
channels:
  - conda-forge
dependencies:
    # Base depends
  - openff-toolkit-examples
    # Tests
  - pytest=7.4
  - pytest-rerunfailures
  - nbval
  - openff-nagl=0.4
  # https://github.com/openforcefield/openff-toolkit/issues/1532
  #- parmed=3