name: latest-deployment
channels:
  - conda-forge

dependencies:
    # Base depends
  - openff-toolkit-examples

  - openmmforcefields >=0.11.2
  - qcportal >=0.15
  - pytest
  - pytest-rerunfailures
  - nbval
