version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"

python:
  install:
    - method: pip
      path: .

conda:
  environment: docs/environment.yml

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
- pdf
