[tool.ruff]
line-length = 119
exclude = ["examples/deprecated/", "utilities/deprecated"]

[tool.ruff.lint]
ignore = ["E721","D105","D107","D200","D203","D212", "RUF012"]
select = ["I", "E", "F", "W", "NPY", "UP", "RUF"]

[tool.ruff.lint.per-file-ignores]
"openff/toolkit/**/__init__.py" = ["F401"]
"openff/toolkit/_version.py" = ["UP", "RUF"]
"openff/toolkit/_tests/**/*.py" = ["E501"]
"openff/toolkit/typing/engines/smirnoff.parameters.py" = ["RUF012"]
"openff/toolkit/_tests/_stale_tests.py" = ["F821"]
"docs/users/molecule_cookbook.ipynb" = ["F821", "E402"]
"examples/visualization/visualization.ipynb" = ["F821"]

[tool.ruff.lint.isort]
# can't find a clean way to get Rust's globset to handle this via regex ...
# https://docs.astral.sh/ruff/settings/#lint_isort_known-third-party
known-third-party = ["openff.interchange", "openff.utilities", "openff.units"]
known-first-party = ["openff.toolkit"]

