package:
  name: openforcefield
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pandas

  run:
    - python
    - numpy
    - networkx ==1.11
    - lxml
    - icu 58*  # This is a lxml dependency but sometimes conda installs version 56
    - openmoltools >=0.7.3
    - parmed
    - matplotlib
    - pandas

test:
  requires:
    - nose
    - nose-timer
  imports:
    - openforcefield

about:
  home: https://github.com/open-forcefield-group/openforcefield
  license: MIT
