#!/bin/bash

mkdir src
cd src

conda activate binder-env
conda list

git clone https://github.com/openforcefield/openforcefield
cd openforcefield
pip install --no-deps -e .
python -c "import openforcefield; print(openforcefield.__version__); print(openforcefield.__file__)"
