name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "21 0 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: pixi run bash -e {0}

jobs:
  test:
    if: (github.event_name == 'schedule' && github.repository == 'openforcefield/openff-toolkit') || (github.event_name != 'schedule')
    name: Test on ${{ matrix.os }}, ${{ matrix.environment }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        environment:
          - py312base
          - py312ambertools
          - py312openeye
          - py312all
          - py313all
          - py312examples
          - py312examples-openeye

    env:
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt

    steps:
      - uses: actions/checkout@v7

      - name: Set up virtual environment
        uses: prefix-dev/setup-pixi@v0.10.0
        with:
          environments: ${{ matrix.environment }}
          frozen: true

      - name: License OpenEye Toolkits
        if: ${{ contains(matrix.environment, 'openeye') || contains(matrix.environment, 'all') }}
        run: |
          echo "${SECRET_OE_LICENSE}" > ${OE_LICENSE}
          pixi run -e ${{ matrix.environment }} python -c "from openeye import oechem; assert oechem.OEChemIsLicensed()"
        env:
          SECRET_OE_LICENSE: ${{ secrets.OE_LICENSE }}

      - name: Run mypy
        if: ${{ contains(matrix.environment, 'all') }}
        run: pixi run -e ${{ matrix.environment }} run_mypy

      - name: Run unit tests
        if: ${{ !contains(matrix.environment, 'examples') }}
        run: pixi run -e ${{ matrix.environment }} run_tests
       
        # TODO: The three pytest+docs runners can be Pixi tasks
      - name: Run code snippets in docs
        if: ${{ contains(matrix.environment, 'all') }}
        run: pixi run -e ${{ matrix.environment }} pytest -v --no-cov --doctest-glob="docs/*.rst" --doctest-glob="docs/*.md" docs/

      - name: Run notebooks in docs
        if: ${{ contains(matrix.environment, 'all') }}
        run: pixi run -e ${{ matrix.environment }} python -m pytest -v --durations=10 --no-cov --nbval-lax docs/

      - name: Run examples in docstrings
        if: ${{ contains(matrix.environment, 'all') }}
        run: |
          pixi run -e ${{ matrix.environment }} pytest openff \
            -v -x -n logical --no-cov --doctest-modules \
            --ignore-glob='openff/toolkit/_tests*' \
            --ignore=openff/toolkit/data/ \
            --ignore=openff/toolkit/utils/utils.py

      - name: Run example scripts
        if: ${{ contains(matrix.environment, 'examples') }}
        run: |
          pixi run -e ${{ matrix.environment }} run_example_scripts

      - name: Run example notebooks
        if: ${{ contains(matrix.environment, 'examples') }}
        run: pixi run -e ${{ matrix.environment }} run_examples

      - name: Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          disable_search: true
          fail_ci_if_error: true

      - name: Check links
        if: ${{ contains(matrix.environment, 'all') }}
        run: pytest -r fE --tb=short openff/toolkit/_tests/test_links.py
