name: Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  test:
    if: (github.event_name == 'schedule' && github.repository == 'openforcefield/openff-toolkit') || (github.event_name != 'schedule')
    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}, RDKit=${{ matrix.rdkit }}, OpenEye=${{ matrix.openeye }}, NAGL=${{ matrix.nagl }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [ "3.12"]
        environment:
          - examples-ambertools
          - examples-openeye

    env:
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up virtual environment
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.70.0
          environments: ${{ matrix.environment }}
          frozen: true

      - name: Make oe_license.txt file from GH org secret "OE_LICENSE"
        if: contains(matrix.environment, 'openeye')
        env:
          OE_LICENSE_TEXT: ${{ secrets.OE_LICENSE }}
        run: echo "${OE_LICENSE_TEXT}" > ${OE_LICENSE}

      - name: Check OpenEye installed
        if: contains(matrix.environment, 'openeye')
        run: |
          pixi run -e examples-openeye python -c "from openff.toolkit.utils.toolkits import OPENEYE_AVAILABLE; assert OPENEYE_AVAILABLE, 'OpenEye unavailable'"

      - name: Check OpenEye NOT installed
        if: ! contains(matrix.environment, 'openeye')
        run: |
          pixi run -e examples-ambertools python -c "from openff.toolkit.utils.toolkits import OPENEYE_AVAILABLE; assert not OPENEYE_AVAILABLE, 'OpenEye available but shouldn\'t be'"

      - name: Run example scripts
        run: pixi run -e ${{ matrix.environment }} run_scripts

      - name: Run example notebooks
        run: pixi run -e ${{ matrix.environment }} run_notebooks
