name: Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    if: (github.event_name == 'schedule' && github.repository == 'openforcefield/openff-toolkit') || (github.event_name != 'schedule')
    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}, RDKit=${{ matrix.rdkit }}, OpenEye=${{ matrix.openeye }}, NAGL=${{ matrix.nagl }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [ "3.12"]
        rdkit: [true]
        openeye: [true, false]
        nagl: [true]

    env:
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt
      PACKAGE: openff
      PYTEST_ARGS: -r fE -v -x --tb=short -nauto --durations=10
      NB_ARGS: --nbval-lax --dist loadscope --ignore=examples/deprecated

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install base conda environment
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: devtools/conda-envs/base-examples.yaml
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install OpenEye toolkits
        if: ${{ matrix.openeye == true }}
        run: micromamba install -c openeye "openeye-toolkits >=2024" -y

      - name: Make oe_license.txt file from GH org secret "OE_LICENSE"
        if: ${{ matrix.openeye == true }}
        env:
          OE_LICENSE_TEXT: ${{ secrets.OE_LICENSE }}
        run: echo "${OE_LICENSE_TEXT}" > ${OE_LICENSE}

      - name: Install package
        run: python -m pip install .

      - name: Check OpenEye installed
        if: ${{ matrix.openeye == true }}
        run: |
          python -c "from openff.toolkit.utils.toolkits import OPENEYE_AVAILABLE; assert OPENEYE_AVAILABLE, 'OpenEye unavailable'"

      - name: Check OpenEye NOT installed
        if: ${{ matrix.openeye == false }}
        run: |
          python -c "from openff.toolkit.utils.toolkits import OPENEYE_AVAILABLE; assert not OPENEYE_AVAILABLE, 'OpenEye available but shouldn\'t be'"

      - name: Environment Information
        run: |
          micromamba info
          micromamba list
          pip list

      - name: Run example scripts
        run: |
          pytest $PYTEST_ARGS openff/toolkit/_tests/test_examples.py

      - name: Run example notebooks
        run: |
          # GROMACS builds are not stable on macOS + GHA
          if [[ ${{ matrix.os }} == macos-latest ]]; then
            NB_ARGS+=" --ignore=examples/using_smirnoff_in_amber_or_gromacs/"
          fi

          python -m pytest $PYTEST_ARGS $NB_ARGS examples
